name: Scan with CLI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        always-auth: true
        node-version: 16
        cache: 'npm'

    - run: npm config set registry https://iq.ajoanes.ngrok.io/ --auth-type=oauth
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - run: npm ci


    - name: Pull Sonatype CLI with wget
      uses: wei/wget@v1
      with:
        args: -O latest.jar https://download.sonatype.com/clm/scanner/latest.jar

    - name: Trigger Sonatype Scan
      run: |
        java -version
        java -jar latest.jar -s https://iq.ajoanes.ngrok.io/ -a 'admin:iqAj610298!'  -t build -i gitActionsScan .
