name: Java with Nexus Repository

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml -Drat.numUnapprovedLicenses=200 -X
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://repo.ajoanes.ngrok.io
        username: admin
        password: admin1234
        format: maven2
        repository: maven-proxy
        coordinates: groupId=org.apache.commons artifactId=commons-lang3 version=3.14.0
        assets: extension=jar
        filename: ./target/commons-lang3@3.14.0
